"""Refactor quiz to single table with JSONB

Revision ID: b7efb7dd5245
Revises: c67267cfe6ee
Create Date: 2026-04-25 20:57:39.065297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7efb7dd5245"
down_revision: Union[str, Sequence[str], None] = "c67267cfe6ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Remove the constraint first to avoid DependentObjectsStillExistError
    op.execute('ALTER TABLE quiz_answers DROP CONSTRAINT IF EXISTS fk_quiz_answers_question_id_quiz_questions')

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "answers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz")),
    )
    op.create_index(op.f("ix_quiz_id"), "quiz", ["id"], unique=False)
    op.drop_index(op.f("ix_quiz_questions_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_index(op.f("ix_quiz_answers_id"), table_name="quiz_answers")
    op.drop_table("quiz_answers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_answers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("text", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("experience_score", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_answers_question_id_quiz_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_answers")),
    )
    op.create_index(op.f("ix_quiz_answers_id"), "quiz_answers", ["id"], unique=False)
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
    )
    op.create_index(
        op.f("ix_quiz_questions_id"), "quiz_questions", ["id"], unique=False
    )
    op.drop_index(op.f("ix_quiz_id"), table_name="quiz")
    op.drop_table("quiz")
    # ### end Alembic commands ###
