"""init

Revision ID: c67267cfe6ee
Revises:
Create Date: 2026-04-24 17:19:01.507873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c67267cfe6ee"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("duration", sa.String(length=255), nullable=True),
        sa.Column("feature", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=True),
        sa.Column("image_path", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    op.create_index(op.f("ix_courses_id"), "courses", ["id"], unique=False)
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    op.create_table(
        "faqs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(length=255), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faqs")),
    )
    op.create_index(op.f("ix_faqs_id"), "faqs", ["id"], unique=False)
    op.create_table(
        "globals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("office_address", sa.String(length=255), nullable=True),
        sa.Column("footer_copyright", sa.String(length=255), nullable=True),
        sa.Column("footer_description", sa.Text(), nullable=True),
        sa.Column("footer_license", sa.String(length=255), nullable=True),
        sa.Column("cookie_banner_text", sa.Text(), nullable=True),
        sa.Column("cookie_banner_btn_accept", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_globals")),
    )
    op.create_index(op.f("ix_globals_id"), "globals", ["id"], unique=False)
    op.create_table(
        "landing_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hero_highlight", sa.String(length=255), nullable=True),
        sa.Column("hero_main_text", sa.String(length=255), nullable=True),
        sa.Column("hero_stat_1_val", sa.String(length=255), nullable=True),
        sa.Column("hero_stat_1_desc", sa.String(length=255), nullable=True),
        sa.Column("hero_stat_2_val", sa.String(length=255), nullable=True),
        sa.Column("hero_stat_2_desc", sa.String(length=255), nullable=True),
        sa.Column("hero_stat_3_val", sa.String(length=255), nullable=True),
        sa.Column("hero_stat_3_desc", sa.String(length=255), nullable=True),
        sa.Column("courses_title", sa.String(length=255), nullable=True),
        sa.Column("courses_desc_1", sa.Text(), nullable=True),
        sa.Column("courses_desc_2", sa.Text(), nullable=True),
        sa.Column("quiz_start_title", sa.String(length=255), nullable=True),
        sa.Column("quiz_start_desc", sa.Text(), nullable=True),
        sa.Column("quiz_result_title", sa.String(length=255), nullable=True),
        sa.Column("quiz_result_subtitle", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_landing_page")),
    )
    op.create_index(op.f("ix_landing_page_id"), "landing_page", ["id"], unique=False)
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("additional_content", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
    )
    op.create_index(op.f("ix_pages_id"), "pages", ["id"], unique=False)
    op.create_index(op.f("ix_pages_slug"), "pages", ["slug"], unique=True)
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
    )
    op.create_index(
        op.f("ix_quiz_questions_id"), "quiz_questions", ["id"], unique=False
    )
    op.create_table(
        "ui_dictionary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ui_dictionary")),
    )
    op.create_index(op.f("ix_ui_dictionary_id"), "ui_dictionary", ["id"], unique=False)
    op.create_index(op.f("ix_ui_dictionary_key"), "ui_dictionary", ["key"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("totp_secret", sa.String(), nullable=True),
        sa.Column("is_2fa_enabled", sa.Boolean(), nullable=True),
        sa.Column("recovery_codes", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "quiz_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("experience_score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_answers_question_id_quiz_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_answers")),
    )
    op.create_index(op.f("ix_quiz_answers_id"), "quiz_answers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_answers_id"), table_name="quiz_answers")
    op.drop_table("quiz_answers")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ui_dictionary_key"), table_name="ui_dictionary")
    op.drop_index(op.f("ix_ui_dictionary_id"), table_name="ui_dictionary")
    op.drop_table("ui_dictionary")
    op.drop_index(op.f("ix_quiz_questions_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_index(op.f("ix_pages_slug"), table_name="pages")
    op.drop_index(op.f("ix_pages_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_landing_page_id"), table_name="landing_page")
    op.drop_table("landing_page")
    op.drop_index(op.f("ix_globals_id"), table_name="globals")
    op.drop_table("globals")
    op.drop_index(op.f("ix_faqs_id"), table_name="faqs")
    op.drop_table("faqs")
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_index(op.f("ix_courses_id"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
