"""sync_models_with_json_data

Revision ID: 8a9ac76bb38f
Revises: b2db0d085533
Create Date: 2026-04-09 19:10:03.175769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9ac76bb38f'
down_revision: Union[str, Sequence[str], None] = 'b2db0d085533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_free', sa.Boolean(), nullable=True))
    op.add_column('globals', sa.Column('footer_copyright', sa.String(length=255), nullable=True))
    op.add_column('globals', sa.Column('footer_description', sa.Text(), nullable=True))
    op.add_column('globals', sa.Column('footer_license', sa.String(length=255), nullable=True))
    op.add_column('globals', sa.Column('cookie_banner_text', sa.Text(), nullable=True))
    op.add_column('globals', sa.Column('cookie_banner_btn_accept', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_highlight', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_main_text', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_1_val', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_1_desc', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_2_val', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_2_desc', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_3_val', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_3_desc', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('courses_title', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('courses_desc_1', sa.Text(), nullable=True))
    op.add_column('landing_page', sa.Column('courses_desc_2', sa.Text(), nullable=True))
    op.add_column('landing_page', sa.Column('quiz_start_title', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('quiz_start_desc', sa.Text(), nullable=True))
    op.add_column('landing_page', sa.Column('quiz_result_title', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('quiz_result_subtitle', sa.String(length=255), nullable=True))
    op.drop_column('landing_page', 'hero_subtitle')
    op.drop_column('landing_page', 'hero_title')
    op.alter_column('pages', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('pages', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.add_column('landing_page', sa.Column('hero_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_subtitle', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('landing_page', 'quiz_result_subtitle')
    op.drop_column('landing_page', 'quiz_result_title')
    op.drop_column('landing_page', 'quiz_start_desc')
    op.drop_column('landing_page', 'quiz_start_title')
    op.drop_column('landing_page', 'courses_desc_2')
    op.drop_column('landing_page', 'courses_desc_1')
    op.drop_column('landing_page', 'courses_title')
    op.drop_column('landing_page', 'hero_stat_3_desc')
    op.drop_column('landing_page', 'hero_stat_3_val')
    op.drop_column('landing_page', 'hero_stat_2_desc')
    op.drop_column('landing_page', 'hero_stat_2_val')
    op.drop_column('landing_page', 'hero_stat_1_desc')
    op.drop_column('landing_page', 'hero_stat_1_val')
    op.drop_column('landing_page', 'hero_main_text')
    op.drop_column('landing_page', 'hero_highlight')
    op.drop_column('globals', 'cookie_banner_btn_accept')
    op.drop_column('globals', 'cookie_banner_text')
    op.drop_column('globals', 'footer_license')
    op.drop_column('globals', 'footer_description')
    op.drop_column('globals', 'footer_copyright')
    op.drop_column('courses', 'is_free')
    # ### end Alembic commands ###
