"""init

Revision ID: aebd67faa4c8
Revises: 
Create Date: 2026-04-12 15:43:33.645010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebd67faa4c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('experience_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_id'), 'quiz_answers', ['id'], unique=False)
    op.add_column('courses', sa.Column('price', sa.Integer(), nullable=True))
    op.alter_column('courses', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.alter_column('faqs', 'question',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('faqs', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_faqs_id'), 'faqs', ['id'], unique=False)
    op.create_index(op.f('ix_globals_id'), 'globals', ['id'], unique=False)
    op.create_index(op.f('ix_landing_page_id'), 'landing_page', ['id'], unique=False)
    op.alter_column('pages', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index(op.f('ix_pages_slug'), 'pages', ['slug'], unique=True)
    op.alter_column('ui_dictionary', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('ui_dictionary', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_ui_dictionary_id'), 'ui_dictionary', ['id'], unique=False)
    op.create_index(op.f('ix_ui_dictionary_key'), 'ui_dictionary', ['key'], unique=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('users', sa.Column('recovery_codes', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'recovery_codes')
    op.drop_column('users', 'totp_secret')
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_ui_dictionary_key'), table_name='ui_dictionary')
    op.drop_index(op.f('ix_ui_dictionary_id'), table_name='ui_dictionary')
    op.alter_column('ui_dictionary', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ui_dictionary', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.alter_column('pages', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('pages', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_index(op.f('ix_landing_page_id'), table_name='landing_page')
    op.drop_index(op.f('ix_globals_id'), table_name='globals')
    op.drop_index(op.f('ix_faqs_id'), table_name='faqs')
    op.alter_column('faqs', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('faqs', 'question',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('courses', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_column('courses', 'price')
    op.drop_index(op.f('ix_quiz_answers_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    # ### end Alembic commands ###
