"""create_users_table_safe

Revision ID: b2db0d085533
Revises: f7c7467f618e
Create Date: 2026-04-09 18:32:12.720061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2db0d085533'
down_revision: Union[str, Sequence[str], None] = 'f7c7467f618e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('recovery_codes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('experience_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_answers_id'), 'quiz_answers', ['id'], unique=False)
    op.add_column('courses', sa.Column('price', sa.Integer(), nullable=True))
    op.alter_column('courses', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.drop_column('courses', 'is_free')
    op.alter_column('faqs', 'question',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('faqs', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_faqs_id'), 'faqs', ['id'], unique=False)
    op.create_index(op.f('ix_globals_id'), 'globals', ['id'], unique=False)
    op.drop_column('globals', 'footer_license')
    op.drop_column('globals', 'cookie_banner_btn_accept')
    op.drop_column('globals', 'cookie_banner_text')
    op.drop_column('globals', 'footer_copyright')
    op.drop_column('globals', 'footer_description')
    op.add_column('landing_page', sa.Column('hero_title', sa.String(length=255), nullable=True))
    op.add_column('landing_page', sa.Column('hero_subtitle', sa.Text(), nullable=True))
    op.create_index(op.f('ix_landing_page_id'), 'landing_page', ['id'], unique=False)
    op.drop_column('landing_page', 'hero_stat_3_desc')
    op.drop_column('landing_page', 'hero_stat_1_val')
    op.drop_column('landing_page', 'courses_title')
    op.drop_column('landing_page', 'hero_stat_3_val')
    op.drop_column('landing_page', 'courses_desc_2')
    op.drop_column('landing_page', 'quiz_start_desc')
    op.drop_column('landing_page', 'hero_stat_2_val')
    op.drop_column('landing_page', 'hero_stat_1_desc')
    op.drop_column('landing_page', 'hero_main_text')
    op.drop_column('landing_page', 'quiz_result_subtitle')
    op.drop_column('landing_page', 'courses_desc_1')
    op.drop_column('landing_page', 'quiz_result_title')
    op.drop_column('landing_page', 'hero_stat_2_desc')
    op.drop_column('landing_page', 'hero_highlight')
    op.drop_column('landing_page', 'quiz_start_title')
    op.alter_column('ui_dictionary', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('ui_dictionary', 'value',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_ui_dictionary_id'), 'ui_dictionary', ['id'], unique=False)
    op.create_index(op.f('ix_ui_dictionary_key'), 'ui_dictionary', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ui_dictionary_key'), table_name='ui_dictionary')
    op.drop_index(op.f('ix_ui_dictionary_id'), table_name='ui_dictionary')
    op.alter_column('ui_dictionary', 'value',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ui_dictionary', 'key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.add_column('landing_page', sa.Column('quiz_start_title', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_highlight', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_2_desc', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('quiz_result_title', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('courses_desc_1', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('quiz_result_subtitle', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_main_text', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_1_desc', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_2_val', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('quiz_start_desc', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('courses_desc_2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_3_val', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('courses_title', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_1_val', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('landing_page', sa.Column('hero_stat_3_desc', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_landing_page_id'), table_name='landing_page')
    op.drop_column('landing_page', 'hero_subtitle')
    op.drop_column('landing_page', 'hero_title')
    op.add_column('globals', sa.Column('footer_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('globals', sa.Column('footer_copyright', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('globals', sa.Column('cookie_banner_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('globals', sa.Column('cookie_banner_btn_accept', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.add_column('globals', sa.Column('footer_license', sa.VARCHAR(length=255), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_globals_id'), table_name='globals')
    op.drop_index(op.f('ix_faqs_id'), table_name='faqs')
    op.alter_column('faqs', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('faqs', 'question',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.add_column('courses', sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('courses', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.drop_column('courses', 'price')
    op.drop_index(op.f('ix_quiz_answers_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    # ### end Alembic commands ###
